'\" t
.TH "DIFFUSE" "1" "2014\-07\-18" "diffuse 0\&.4\&.8" "Руководство по Diffuse"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "НАЗВАНИЕ"
diffuse \- графический инструмент для слияния и сравнения текстовых файлов
.SH "СИНТАКСИС"
.HP \w'\fBdiffuse\fR\ 'u
\fBdiffuse\fR [\fB\-h\fR | \fB\-?\fR | \fB\-\-help\fR | \fB\-v\fR | \fB\-\-version\fR]
.HP \w'\fBdiffuse\fR\ 'u
\fBdiffuse\fR [\fB\-\-no\-rcfile\fR | \fB\-\-rcfile\ \fR\fB\fIfile\fR\fR] [[\fIoption\fR...] | [\fIfile\fR...]...]
.SH "ОПИСАНИЕ"
.PP
Программа
Diffuse
является графическим инструментом для слияния и сравнения текстовых файлов\&. Она может сравнить произвольное число файлов в представлении бок о бок, предоставляет пользователям возможность вручную корректировать соответствие строк и редактировать файлы напрямую\&.
Diffuse
может также извлекать ревизии файлов из Bazaar, CVS, Darcs, Git, Mercurial, Monotone, RCS и Subversion репозиториев для их сравнения и слияния\&.
.SH "ОПЦИИ"
.SS "Параметры Справки"
.PP
Если опция справки определена, только параметр должен быть указан в командной строке\&. Программа
Diffuse
немедленно закроется после отображения справочной информации\&.
.PP
\fB\-h\fR, \fB\-?\fR, \fB\-\-help\fR
.RS 4
Отобразить информацию по использованию\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Отобразить информацию о номере версии и авторских правах\&.
.RE
.SS "Параметры Конфигурации"
.PP
Если опция конфигурации определена, она должна быть первым параметром, указываемым в командной строке\&.
.PP
\fB\-\-no\-rcfile\fR
.RS 4
Не читать файлы инициализации\&.
.RE
.PP
\fB\-\-rcfile \fR\fB\fIfile\fR\fR
.RS 4
Только прочитать команды инициализации из файла под именем
\fIfile\fR\&.
.RE
.SS "Общие Параметры"
.PP
\fB\-c\fR, \fB\-\-commit\fR \fIrev\fR
.RS 4
Открыть отдельные вкладки сравнения файлов для всех файлов, затрагиваемых фиксацией
\fIrev\fR
из остающихся путей, определенных в параметрах командной строки\&.
.RE
.PP
\fB\-D\fR, \fB\-\-close\-if\-same\fR
.RS 4
Закрыть все не имеющие различий вкладки\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encoding\fR \fIcodec\fR
.RS 4
Использовать
\fIcodec\fR
(кодек) для чтения и записи файлов\&.
.RE
.PP
\fB\-L\fR, \fB\-\-label\fR \fIlabel\fR
.RS 4
Отображать
\fIlabel\fR
ярлык вместо имени файла\&.
.RE
.PP
\fB\-m\fR, \fB\-\-modified\fR
.RS 4
Открыть отдельные вкладки сравнения файлов для всех модифицированных файлов из остающихся путей, определенных в параметрах командной строки\&.
.RE
.PP
\fB\-r\fR, \fB\-\-revision\fR \fIrev\fR
.RS 4
Включить ревизию
\fIrev\fR
следующего файла, названного в параметрах командной строки, во вкладку сравнения файлов\&.
.RE
.PP
\fB\-s\fR, \fB\-\-separate\fR
.RS 4
Открыть все остающиеся файлы, определенные в параметрах командной строки, на отдельных вкладках сравнения файлов\&.
.RE
.PP
\fB\-t\fR, \fB\-\-tab\fR
.RS 4
Запустить новую вкладку для любых остающихся файлов, названных в параметрах командной строки\&.
.RE
.PP
\fB\-\-line \fR\fB\fIline\fR\fR
.RS 4
Начать с выбранной
\fIline\fR
строки\&.
.RE
.PP
\fB\-\-null\-file\fR
.RS 4
Создать пустое субокно сравнения файла\&.
.RE
.SS "Параметры Отображения"
.PP
Опции отображения, определенные в параметрах командной строки, имеют приоритет над сохраненными значениями предпочтений\&.
.PP
\fB\-b\fR, \fB\-\-ignore\-space\-change\fR
.RS 4
Игнорировать изменения количества свободного места (пробелы, символы табуляции и пустой строки)\&.
.RE
.PP
\fB\-B\fR, \fB\-\-ignore\-blank\-lines\fR
.RS 4
Игнорировать те изменения, чьи строки все пустые\&.
.RE
.PP
\fB\-E\fR, \fB\-\-ignore\-end\-of\-line\fR
.RS 4
Игнорировать различия окончания строк (терминаторы)\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-case\fR
.RS 4
Игнорировать различия регистра символов в содержании файла\&.
.RE
.PP
\fB\-w\fR, \fB\-\-ignore\-all\-space\fR
.RS 4
Игнорировать все пробелы, символы табуляции и пустой строки\&.
.RE
.SH "СРАВНЕНИЕ ФАЙЛОВ"
.PP
Используйте пункты меню
Файл \(-> Новое 2\-Оконное Слияние Файлов
и
Файл \(-> Новое 3\-Оконное Слияние Файлов, чтобы создать дополнительные вкладки для сравнения текстовых файлов\&. Имена файлов и ревизий могут быть указаны либо в параметрах командной строки, используемых для вызова
Diffuse, либо в полях диалога Открыть Файл\&.
.PP
Программа
Diffuse
отображает файлы бок о бок, вставляя разрывы для выравнивания подобных строк текста\&. Различия выделяются отличным цветом фона\&.
.SS "Сводка Сравнения"
.PP
Сводка сравненных файлов располагается в дальнем правом поле\&. Сводка иллюстрирует, где были вставлены разрывы для выравнивания соответствующих строк текста и подсветку различий, используя цвет\&. Ручные редактирования также выделяются зеленым цветом\&. Синий курсор идентифицирует в настоящий момент просматриваемую область\&. Просматриваемая область может быть изменена щелками где угодно на сводке\&.
.SS "Выборка"
.PP
Строки текста могут быть выбраны, используя указатель мыши или клавиатуру\&. Выбирайте строки текста указателем мыши, щелкая по строке\&. Щелкайте и перетаскивайте указатель для выбора множественных строк\&. Удержание клавиши Shift при щелчке расширит текущий выбор\&. Выбирайте строки текста с клавиатуры, нажимая клавиши страница вверх/страница вниз или клавиши со стрелками\&. Расширяйте текущий выбор удержанием клавиши Shift и нажатием страница вверх/страница вниз или клавиш со стрелками\&. Перемещайте выбор в смежный файл, используя клавиши стрелка влево и стрелка вправо\&.
.SS "Соответствие Строк"
.PP
Указатель мыши или клавиатура могут использоваться для выравнивания (подгонки) строк текста вручную в смежных файлах\&. Чтобы выровнять (подогнать) строки текста указателем мыши, выберите строку текста левой кнопкой мыши, щелкните правой кнопкой мыши по строке текста в смежном файле и выберите пункт всплывающего меню
Выровнять с Выборкой\&. Чтобы выровнять строки текста с клавиатуры, переместите выбор клавишами управления курсором, нажмите клавишу Space (Пробел), чтобы выбрать текущую строку текста, затем переместите выбор клавишами управления курсором на строку текста в смежном файле и нажмите клавишу Space (Пробел), чтобы выбрать целевую строку текста\&. Нажатие клавиши
Escape
отменит эту операцию\&.
.PP
Используйте пункт меню
Изолировать
для предотвращения того, чтобы выбранные строки сопоставлялись любым строкам из смежных файлов\&.
.SS "Редактирование"
.PP
Нажатие клавиши
Enter
или двойной щелчок на области текста для ввода режима редактирования текста\&. Курсор изменится, чтобы указать на включение режима редактирования текста, а строка состояния внизу окна отобразит номер столбца/колонки, где находится курсор (т\&.е\&. по сути, отображается номер символа, находящегося слева от курсора, в текущей строке с учетом пробелов)\&.
.PP
В режиме редактирования текста, текст может быть выбран указателем мыши, щелчком и перетаскиванием курсора\&. Текущий выбор может быть расширен удержанием клавиши Shift и перемещением указателя мыши (т\&.е\&. щелчок в начале требуемого \- нажатие и удержание Shift \- щелчок в конце требуемого) или нажатием любой клавиши\-стрелки, Нome, End или страница вверх/страница вниз\&. Отдельные слова могут быть выбраны двойным щелчком указателя мыши по ним\&. Целые строки могут быть выбраны тройным щелчком указателя мыши по ним\&.
.PP
Изменяйте текст, вводя с клавиатуры\&. Измененные строки будут выделены зеленым цветом\&. Используйте пункты меню
Отменить
и
Вернуть, чтобы отменить и восстановить ранее выполненные операции\&.
.PP
Нажмите клавишу
Еscape
или щелкните левой кнопкой мыши на области текста в другом файле, чтобы выйти из режима редактирования\&.
.SS "Слияние"
.PP
Используйте различные кнопки или пункты меню для перемещения между блоками различий в пределах файла\&. На навигации,
Diffuse
переместит указатель мыши в следующий сплошной набор строк с различиями или редактированиями\&.
.PP
Используйте кнопки слияния или пункты меню, чтобы скопировать блоки текста в выбранный диапазон строк\&. Пункты меню
Отменить
и
Вернуть
могут использоваться для отмены и восстановления ранее выполненных операций\&. Все изменения к набору строк могут быть возвращены к исходному состоянию, используя пункт меню
Очистить Правки
независимо от порядка выполнения редактирований\&.
.SH "КОНТРОЛЬ ВЕРСИЙ"
.PP
Diffuse
может извлекать ревизии файла из нескольких систем управления версиями через их интерфейс командной строки\&. Microsoft Windows сборка
Diffuse
способна использовать как Cygwin, так и собственные версии поддерживаемых систем управления версиями\&. При использовании
Diffuse
с Cygwin, убедитесь, что предпочтения Cygwin программы
Diffuse
правильно описывают вашу систему\&. Если пункт предпочтений
Обновлять пути для Cygwin
существует для данной системы управления версиями, он должен быть задействован для использования версии Cygwin\&.
.PP
Системы управления версиями чувствительны к системному пути и к другим настройкам среды\&. Пункт предпочтений
Запуск из оболочки Bash login
может использоваться, чтобы легко установить среду для Cygwin систем управления версиями\&.
.SS "Просмотр Незафиксированных Модификаций"
.PP
Опция
\fB\-m\fR
заставит
Diffuse
открывать вкладки сравнения для каждого файла, на который указывает система управления версиями, как на имеющий незафиксированные (несвязанные) модификации\&. Это удобно для просмотра всех изменений перед фиксацией транзакции или разрешением конфликта слияния\&. Если никакие пути не будут определены, то текущий рабочий каталог будет использоваться\&. Например, можно просмотреть все свои незафиксированные модификации с этой командной строкой:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-m\fR
.fi
.if n \{\
.RE
.\}
.PP
Ревизия по умолчанию файла будет использоваться для сравнения, если только один файл будет определен\&. Например, чтобы отобразить 2\-оконное слияние между ревизией по умолчанию
foo\&.C
и локальным файлом
foo\&.C:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.sp
.SS "Определение Ревизий"
.PP
Опция
\fB\-r\fR
может также использоваться, чтобы явно указать определенную ревизию файла\&. Любой спецификатор ревизии, понятный для системы управления версиями, может использоваться\&. Локальный файл будет использоваться для сравнения, если только одна ревизия файла будет определена\&.Например, чтобы отобразить 2\-оконное слияние между ревизией 123
foo\&.C
и локальным файлом
foo\&.C:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-r 123 foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.PP
Множественные ревизии файла могут быть сравнены вводом множественных опций
\fB\-r\fR
\&. Например, чтобы отобразить 2\-оконное слияние между ревизией 123 файла
foo\&.C
и ревизией 321 файла
foo\&.C:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-r 123 \-r 321 foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.PP
Локальные файлы могут быть смешаны с файлами от системы управления версиями\&. Например, чтобы отобразить 3\-оконное слияние между ревизией MERGE_HEAD файла
foo\&.C, локальным файлом
foo\&.C
и ревизией HEAD файла
foo\&.C:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-r MERGE_HEAD foo\&.C foo\&.C \-r HEAD foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.PP
Опция
\fB\-c\fR
может использоваться, чтобы легко определить пару последовательных ревизий\&. Например, чтобы отобразить 2\-оконное слияние между ревизией 1\&.2\&.2 файла
foo\&.C
и ревизией 1\&.2\&.3 файла
foo\&.C:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-c 1\&.2\&.3 foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.PP
Программа
Diffuse
не ограничивает количество субокон, используемых для сравнения файлов\&. Вводы к Git octopus слиянию могли бы быть просмотрены с командной строкой, как ниже:
.PP
.if n \{\
.RS 4
.\}
.nf
$ \fBdiffuse \-r HEAD^1 \-r HEAD^2 \-r HEAD^3 \-r HEAD^4 \-r HEAD^5 foo\&.C\fR
.fi
.if n \{\
.RE
.\}
.sp
.SH "РЕСУРСЫ"
.PP
Ресурсы могут использоваться для индивидуализации некоторых аспектов внешнего вида программы
Diffuse
и ее поведения, например, изменение используемых в интерфейсе пользователя цветов, настройки клавиатурных комбинаций вызова, добавление или замена правил подсветки синтаксиса или изменение отображения от расширений файла до правил подсветки синтаксиса\&.
.PP
Когда программа
Diffuse
запускается, она считает команды из файла общесистемной инициализации
/etc/diffuserc
(%INSTALL_DIR%\ediffuserc
на Microsoft Windows), а затем считывает персональный файл инициализации
~/\&.config/diffuse/diffuserc
(%HOME%\e\&.config\ediffuse\ediffuserc
на Microsoft Windows)\&. Это поведение может быть изменено при помощи опций конфигурации
\fB\-\-no\-rcfile\fR
и
\fB\-\-rcfile\fR\&. Bourne shell\-like лексический анализатор используется для парсинга (синтаксического анализа/разбора) команд инициализации\&. Комментарии и специальные символы могут быть вставлены, используя тот же самый стиль перехода, который используется в Bourne shell скриптах (сценариях)\&.
.SS "Общее"
.PP
\fBimport \fR\fB\fIfile\fR\fR
.RS 4
Команды инициализации процессов из файла под именем
\fIfile\fR\&. Файлы инициализации будут обработаны только один раз\&.
.RE
.SS "Привязки Клавиш"
.PP
\fBkeybinding \fR\fB\fIcontext\fR\fR\fB \fR\fB\fIaction\fR\fR\fB \fR\fB\fIkey_combination\fR\fR
.RS 4
Командная строка выше служит для привязки сочетаний клавиш к действию
\fIaction\fR, когда используется в
\fIcontext\fR\&. Определяйте модификаторы
Shift
и
Control, присоединением вначале
\fBShift+\fR
и
\fBCtrl+\fR
к
\fIkey_combination\fR
соответственно\&. Клавиши, обычно модифицируемые клавишей
Shift, должны быть определены использованием их модифицированного значения, если
\fIkey_combination\fR
включает клавишу
Shift\&. Например,
\fBCtrl+g\fR
и
\fBShift+Ctrl+G\fR\&. Удаление привязки для
\fIkey_combination\fR
осуществляется определением
\fBNone\fR
для
\fIaction\fR\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПривязки Клавиш Пунктов Меню\fR
.RS 4
.PP
Используйте
\fBmenu\fR
взамен
\fIcontext\fR, чтобы определить привязки клавиш для пунктов меню\&. Следующие значения допустимы для
\fIaction\fR:
.PP
\fBopen_file\fR
.RS 4
Файл \(-> Открыть Файл\&.\&.\&.
.sp
По умолчанию:
Ctrl+o
.RE
.PP
\fBopen_file_in_new_tab\fR
.RS 4
Файл \(-> Открыть Файл в Новой Вкладке\&.\&.\&.
.sp
По умолчанию:
Ctrl+t
.RE
.PP
\fBopen_modified_files\fR
.RS 4
Файл \(-> Открыть Измененные Файлы\&.\&.\&.
.sp
По умолчанию:
Shift+Ctrl+O
.RE
.PP
\fBopen_commit\fR
.RS 4
Файл \(-> Открыть Зафиксированные\&.\&.\&.
.sp
По умолчанию:
Shift+Ctrl+T
.RE
.PP
\fBreload_file\fR
.RS 4
Файл \(-> Перезагрузить Файл
.sp
По умолчанию:
Shift+Ctrl+R
.RE
.PP
\fBsave_file\fR
.RS 4
Файл \(-> Сохранить Файл
.sp
По умолчанию:
Ctrl+s
.RE
.PP
\fBsave_file_as\fR
.RS 4
Файл \(-> Сохранить Файл Как\&.\&.\&.
.sp
По умолчанию:
Shift+Ctrl+A
.RE
.PP
\fBsave_all\fR
.RS 4
Файл \(-> Сохранить Все
.sp
По умолчанию:
Shift+Ctrl+S
.RE
.PP
\fBnew_2_way_file_merge\fR
.RS 4
Файл \(-> Новое 2\-Оконное Слияние Файлов
.sp
По умолчанию:
Ctrl+2
.RE
.PP
\fBnew_3_way_file_merge\fR
.RS 4
Файл \(-> Новое 3\-Оконное Слияние Файлов
.sp
По умолчанию:
Ctrl+3
.RE
.PP
\fBclose_tab\fR
.RS 4
Файл \(-> Закрыть Вкладку
.sp
По умолчанию:
Ctrl+w
.RE
.PP
\fBundo_close_tab\fR
.RS 4
Файл \(-> Отменить Закрытие Вкладки
.sp
По умолчанию:
Shift+Ctrl+w
.RE
.PP
\fBquit\fR
.RS 4
Файл \(-> Bыход
.sp
По умолчанию:
Ctrl+q
.RE
.PP
\fBundo\fR
.RS 4
Правка \(-> Отменить
.sp
По умолчанию:
Ctrl+z
.RE
.PP
\fBredo\fR
.RS 4
Правка \(-> Вернуть
.sp
По умолчанию:
Shift+Ctrl+Z
.RE
.PP
\fBcut\fR
.RS 4
Правка \(-> Вырезать
.sp
По умолчанию:
Ctrl+x
.RE
.PP
\fBcopy\fR
.RS 4
Правка \(-> Копировать
.sp
По умолчанию:
Ctrl+c
.RE
.PP
\fBpaste\fR
.RS 4
Правка \(-> Вставить
.sp
По умолчанию:
Ctrl+v
.RE
.PP
\fBselect_all\fR
.RS 4
Правка \(-> Выбрать Все
.sp
По умолчанию:
Ctrl+a
.RE
.PP
\fBclear_edits\fR
.RS 4
Правка \(-> Очистить Правки
.sp
По умолчанию:
Ctrl+r
.RE
.PP
\fBdismiss_all_edits\fR
.RS 4
Правка \(-> Сбросить Все Правки
.sp
По умолчанию:
Ctrl+d
.RE
.PP
\fBfind\fR
.RS 4
Правка \(-> Найти\&.\&.\&.
.sp
По умолчанию:
Ctrl+f
.RE
.PP
\fBfind_next\fR
.RS 4
Правка \(-> Найти Следующее
.sp
По умолчанию:
Ctrl+g
.RE
.PP
\fBfind_previous\fR
.RS 4
Правка \(-> Найти Предыдущее
.sp
По умолчанию:
Shift+Ctrl+G
.RE
.PP
\fBgo_to_line\fR
.RS 4
Правка \(-> Перейти на Строку\&.\&.\&.
.sp
По умолчанию:
Shift+Ctrl+L
.RE
.PP
\fBpreferences\fR
.RS 4
Правка \(-> Предпочтения\&.\&.\&.
.sp
По умолчанию: Нет
.RE
.PP
\fBno_syntax_highlighting\fR
.RS 4
Вид \(-> Подсветка Синтаксиса \(-> Нет
.sp
По умолчанию: Нет
.RE
.PP
\fBsyntax_highlighting_\fR\fB\fIsyntax\fR\fR
.RS 4
Вид \(-> Подсветка Синтаксиса \(-> \fIsyntax\fR
.sp
По умолчанию: Нет
.RE
.PP
\fBrealign_all\fR
.RS 4
Вид \(-> Перестроить Все
.sp
По умолчанию:
Ctrl+l
.RE
.PP
\fBisolate\fR
.RS 4
Вид \(-> Изолировать
.sp
По умолчанию:
Ctrl+i
.RE
.PP
\fBfirst_difference\fR
.RS 4
Вид \(-> Первое Различие
.sp
По умолчанию:
Shift+Ctrl+Up
.RE
.PP
\fBprevious_difference\fR
.RS 4
Вид \(-> Предыдущее Различие
.sp
По умолчанию:
Ctrl+Up
.RE
.PP
\fBnext_difference\fR
.RS 4
Вид \(-> Следующее Различие
.sp
По умолчанию:
Ctrl+Down
.RE
.PP
\fBlast_difference\fR
.RS 4
Вид \(-> Последнее Различие
.sp
По умолчанию:
Shift+Ctrl+Down
.RE
.PP
\fBfirst_tab\fR
.RS 4
Вид \(-> Первая Вкладка
.sp
По умолчанию:
Shift+Ctrl+Page_Up
.RE
.PP
\fBprevious_tab\fR
.RS 4
Вид \(-> Предыдущая Вкладка
.sp
По умолчанию:
Ctrl+Page_Up
.RE
.PP
\fBnext_tab\fR
.RS 4
Вид \(-> Следующая Вкладка
.sp
По умолчанию:
Ctrl+Page_Down
.RE
.PP
\fBlast_tab\fR
.RS 4
Вид \(-> Последняя Вкладка
.sp
По умолчанию:
Shift+Ctrl+Page_Down
.RE
.PP
\fBshift_pane_right\fR
.RS 4
Вид \(-> Переместить Субокно Вправо
.sp
По умолчанию:
Shift+Ctrl+parenleft
.RE
.PP
\fBshift_pane_left\fR
.RS 4
Вид \(-> сместить выбранное субокно влево
.sp
По умолчанию:
Shift+Ctrl+parenright
.RE
.PP
\fBconvert_to_upper_case\fR
.RS 4
Формат \(-> Преобразовать в Верхний Регистр
.sp
По умолчанию:
Ctrl+u
.RE
.PP
\fBconvert_to_lower_case\fR
.RS 4
Формат \(-> Преобразовать в Нижний Регистр
.sp
По умолчанию:
Shift+Ctrl+U
.RE
.PP
\fBsort_lines_in_ascending_order\fR
.RS 4
Формат \(-> Сортировать Строки в Порядке Возрастания
.sp
По умолчанию:
Ctrl+y
.RE
.PP
\fBsort_lines_in_descending_order\fR
.RS 4
Формат \(-> Сортировать Строки в Порядке Убывания
.sp
По умолчанию:
Shift+Ctrl+Y
.RE
.PP
\fBremove_trailing_white_space\fR
.RS 4
Формат \(-> Удалить Замыкающие Пробелы
.sp
По умолчанию:
Ctrl+k
.RE
.PP
\fBconvert_tabs_to_spaces\fR
.RS 4
Формат \(-> Преобразовать Табуляторы в Пробелы
.sp
По умолчанию:
Ctrl+b
.RE
.PP
\fBconvert_leading_spaces_to_tabs\fR
.RS 4
Формат \(-> Преобразовать Вводные Пробелы в Табуляторы
.sp
По умолчанию:
Shift+Ctrl+B
.RE
.PP
\fBincrease_indenting\fR
.RS 4
Формат \(-> Увеличить Отступ
.sp
По умолчанию:
Shift+Ctrl+greater
.RE
.PP
\fBdecrease_indenting\fR
.RS 4
Формат \(-> Уменьшить Отступ
.sp
По умолчанию:
Shift+Ctrl+less
.RE
.PP
\fBconvert_to_dos\fR
.RS 4
Формат \(-> Преобразовать в DOS Формат
.sp
По умолчанию:
Shift+Ctrl+E
.RE
.PP
\fBconvert_to_mac\fR
.RS 4
Формат \(-> Преобразовать в Maс Формат
.sp
По умолчанию:
Shift+Ctrl+C
.RE
.PP
\fBconvert_to_unix\fR
.RS 4
Формат \(-> Преобразовать в Uniх Формат
.sp
По умолчанию:
Ctrl+e
.RE
.PP
\fBcopy_selection_right\fR
.RS 4
Слияние \(-> Копировать Выборку Вправо
.sp
По умолчанию:
Shift+Ctrl+Right
.RE
.PP
\fBcopy_selection_left\fR
.RS 4
Слияние \(-> Копировать Выборку Влево
.sp
По умолчанию:
Shift+Ctrl+Left
.RE
.PP
\fBcopy_left_into_selection\fR
.RS 4
Слияние \(-> Копировать Слева в Выборку
.sp
По умолчанию:
Ctrl+Right
.RE
.PP
\fBcopy_right_into_selection\fR
.RS 4
Слияние \(-> Копировать Справа в Выборку
.sp
По умолчанию:
Ctrl+Left
.RE
.PP
\fBmerge_from_left_then_right\fR
.RS 4
Слияние \(-> Слияние Слева Затем Справа
.sp
По умолчанию:
Ctrl+m
.RE
.PP
\fBmerge_from_right_then_left\fR
.RS 4
Слияние \(-> Слияние Справа Затем Слева
.sp
По умолчанию:
Shift+Ctrl+M
.RE
.PP
\fBhelp_contents\fR
.RS 4
Справка \(-> Содержание Справки\&.\&.\&.
.sp
По умолчанию:
F1
.RE
.PP
\fBabout\fR
.RS 4
Справка \(-> О программе Diffuse\&.\&.\&.
.sp
По умолчанию: Нет
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПривязки Клавиш Режима Редактирования Строк\fR
.RS 4
.PP
Используйте
\fBline_mode\fR
для
\fIcontext\fR, чтобы определить привязки клавиш для режима редактирования строк\&. Следующие значения допустимы для
\fIaction\fR:
.PP
\fBenter_align_mode\fR
.RS 4
ввести режим редактирования выравнивания
.sp
По умолчанию:
space
.RE
.PP
\fBenter_character_mode\fR
.RS 4
ввести режим редактирования символов
.sp
По умолчаниям:
Return,
KP_Enter
.RE
.PP
\fBfirst_line\fR
.RS 4
переместить курсор на первую строку
.sp
По умолчаниям:
Home,
g
.RE
.PP
\fBextend_first_line\fR
.RS 4
переместить курсор на первую строку, расширение выборки
.sp
По умолчанию:
Shift+Home
.RE
.PP
\fBlast_line\fR
.RS 4
переместить курсор на последнюю строку
.sp
По умолчаниям:
End,
Shift+G
.RE
.PP
\fBextend_last_line\fR
.RS 4
переместить курсор на последнюю строку, расширение выборки
.sp
По умолчанию:
Shift+End
.RE
.PP
\fBup\fR
.RS 4
переместить курсор на одну строку вверх
.sp
По умолчаниям:
Up,
k
.RE
.PP
\fBextend_up\fR
.RS 4
переместить курсор на одну строку вверх, расширение выборки
.sp
По умолчаниям:
Shift+Up,
Shift+K
.RE
.PP
\fBdown\fR
.RS 4
переместить курсор на одну строку вниз
.sp
По умолчаниям:
Down,
j
.RE
.PP
\fBextend_down\fR
.RS 4
переместить курсор на одну строку вниз, расширение выборки
.sp
По умолчаниям:
Shift+Down,
Shift+J
.RE
.PP
\fBleft\fR
.RS 4
переместить курсор влево на один файл
.sp
По умолчаниям:
Left,
h
.RE
.PP
\fBextend_left\fR
.RS 4
переместить курсор влево на один файл, расширение выборки
.sp
По умолчанию:
Shift+Left
.RE
.PP
\fBright\fR
.RS 4
переместить курсор вправо на один файл
.sp
По умолчаниям:
Right,
l
.RE
.PP
\fBextend_right\fR
.RS 4
переместить курсор вправо на один файл, расширение выборки
.sp
По умолчанию:
Shift+Right
.RE
.PP
\fBpage_up\fR
.RS 4
переместить курсор на одну страницу вверх
.sp
По умолчаниям:
Page_Up,
Ctrl+u
.RE
.PP
\fBextend_page_up\fR
.RS 4
переместить курсор на одну страницу вверх, расширение выборки
.sp
По умолчаниям:
Shift+Page_Up,
Shift+Ctrl+u
.RE
.PP
\fBpage_down\fR
.RS 4
переместить курсор на одну страницу вниз
.sp
По умолчаниям:
Page_Down,
Ctrl+d
.RE
.PP
\fBextend_page_down\fR
.RS 4
переместить курсор на одну страницу вниз, расширение выборки
.sp
По умолчаниям:
Shift+Page_Down,
Shift+Ctrl+d
.RE
.PP
\fBdelete_text\fR
.RS 4
удалить выбранный текст
.sp
По умолчаниям:
BackSpace,
Delete,
x
.RE
.PP
\fBfirst_difference\fR
.RS 4
выбрать первое различие
.sp
По умолчаниям:
Ctrl+Home,
Shift+P
.RE
.PP
\fBprevious_difference\fR
.RS 4
выбрать предыдущее различие
.sp
По умолчанию:
p
.RE
.PP
\fBnext_difference\fR
.RS 4
выбрать следующее различие
.sp
По умолчанию:
n
.RE
.PP
\fBlast_difference\fR
.RS 4
выбрать последнее различие
.sp
По умолчаниям:
Ctrl+End,
Shift+N
.RE
.PP
\fBclear_edits\fR
.RS 4
очистить все редактирования в выбранных строках
.sp
По умолчанию:
r
.RE
.PP
\fBcopy_selection_right\fR
.RS 4
Слияние \(-> Копировать Выборку Вправо
.sp
По умолчанию: Нет
.RE
.PP
\fBcopy_selection_left\fR
.RS 4
Слияние \(-> Копировать Выборку Влево
.sp
По умолчанию: Нет
.RE
.PP
\fBcopy_left_into_selection\fR
.RS 4
копировать строки из файла слева в выборку
.sp
По умолчанию:
Shift+L
.RE
.PP
\fBcopy_right_into_selection\fR
.RS 4
копировать строки из файла справа в выборку
.sp
По умолчанию:
Shift+H
.RE
.PP
\fBmerge_from_left_then_right\fR
.RS 4
объединить строки из файла слева, затем из файла справа
.sp
По умолчанию:
m
.RE
.PP
\fBmerge_from_right_then_left\fR
.RS 4
объединить строки из файла справа, затем из файла слева
.sp
По умолчанию:
Shift+M
.RE
.PP
\fBisolate\fR
.RS 4
изолировать выбранные строки
.sp
По умолчанию:
i
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПривязки Клавиш Режима Редактирования Выравнивания\fR
.RS 4
.PP
Используйте
\fBalign_mode\fR
для
\fIcontext\fR, чтобы определить привязки клавиш для режима редактирования выравнивания\&. Следующие значения допустимы для
\fIaction\fR:
.PP
\fBenter_line_mode\fR
.RS 4
ввести режим редактирования строк
.sp
По умолчанию:
Escape
.RE
.PP
\fBenter_character_mode\fR
.RS 4
ввести режим редактирования символов
.sp
По умолчаниям:
Return,
KP_Enter
.RE
.PP
\fBfirst_line\fR
.RS 4
переместить курсор на первую строку
.sp
По умолчанию:
g
.RE
.PP
\fBlast_line\fR
.RS 4
переместить курсор на последнюю строку
.sp
По умолчанию:
Shift+G
.RE
.PP
\fBup\fR
.RS 4
переместить курсор на одну строку вверх
.sp
По умолчаниям:
Up,
k
.RE
.PP
\fBdown\fR
.RS 4
переместить курсор на одну строку вниз
.sp
По умолчаниям:
Down,
j
.RE
.PP
\fBleft\fR
.RS 4
переместить курсор влево на один файл
.sp
По умолчаниям:
Left,
h
.RE
.PP
\fBright\fR
.RS 4
переместить курсор вправо на один файл
.sp
По умолчаниям:
Right,
l
.RE
.PP
\fBpage_up\fR
.RS 4
переместить курсор на одну страницу вверх
.sp
По умолчаниям:
Page_Up,
Ctrl+u
.RE
.PP
\fBpage_down\fR
.RS 4
переместить курсор на одну страницу вниз
.sp
По умолчаниям:
Page_Down,
Ctrl+d
.RE
.PP
\fBalign\fR
.RS 4
выровнять выбранную строку к позиции курсора
.sp
По умолчанию:
space
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПривязки Клавиш Режима Редактирования Символов\fR
.RS 4
.PP
Используйте
\fBcharacter_mode\fR
для
\fIcontext\fR, чтобы определить привязки клавиш для режима редактирования символов\&. Следующие значения допустимы для
\fIaction\fR:
.PP
\fBenter_line_mode\fR
.RS 4
ввести режим редактирования строк
.sp
По умолчанию:
Escape
.RE
.RE
.SS "Строки"
.PP
\fBstring \fR\fB\fIname\fR\fR\fB \fR\fB\fIvalue\fR\fR
.RS 4
Объявить строковый ресурс под именем
\fIname\fR
со значением
\fIvalue\fR\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBИспользуемые Строковые Ресурсы\fR
.RS 4
.PP
Следующие строковые ресурсы используются программой
Diffuse:
.PP
\fBdifference_colours\fR
.RS 4
список ресурсов цвета, используемых для индикации различий
.sp
По умолчанию:
difference_1 difference_2 difference_3
.RE
.RE
.SS "Цвета"
.PP
\fB[ colour | color ] \fR\fB\fIname\fR\fR\fB \fR\fB\fIred\fR\fR\fB \fR\fB\fIgreen\fR\fR\fB \fR\fB\fIblue\fR\fR
.RS 4
Объявить цветовой ресурс, называемый
\fIname\fR\&. Отдельные компоненты цвета должны быть выражены как значение между 0 и 1\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBИспользуемые Цветовые Ресурсы\fR
.RS 4
.PP
Следующие ресурсы цвета используются программой
Diffuse:
.PP
\fBalignment\fR
.RS 4
цвет, используемый для индикации строки, выбранной для ручного выравнивания
.sp
По умолчанию:
1 1 0
.RE
.PP
\fBcharacter_selection\fR
.RS 4
цвет, используемый для индикации выбранных символов
.sp
По умолчанию:
0\&.7 0\&.7 1
.RE
.PP
\fBcursor\fR
.RS 4
цвет, используемый для курсора
.sp
По умолчанию:
0 0 0
.RE
.PP
\fBdifference_1\fR
.RS 4
цвет, используемый для обозначения различий между первой парой файлов
.sp
По умолчанию:
1 0\&.625 0\&.625
.RE
.PP
\fBdifference_2\fR
.RS 4
цвет, используемый для обозначения различий между второй парой файлов
.sp
По умолчанию:
0\&.85 0\&.625 0\&.775
.RE
.PP
\fBdifference_3\fR
.RS 4
цвет, используемый для обозначения различий между третьей парой файлов
.sp
По умолчанию:
0\&.85 0\&.775 0\&.625
.RE
.PP
\fBedited\fR
.RS 4
цвет, используемый для индикации отредактированных строк
.sp
По умолчанию:
0\&.5 1 0\&.5
.RE
.PP
\fBhatch\fR
.RS 4
цвет, используемый для индикации разрывов выравнивания
.sp
По умолчанию:
0\&.8 0\&.8 0\&.8
.RE
.PP
\fBline_number\fR
.RS 4
цвет, используемый для номеров строк
.sp
По умолчанию:
0 0 0
.RE
.PP
\fBline_number_background\fR
.RS 4
цвет фона для области номера строки
.sp
По умолчанию:
0\&.75 0\&.75 0\&.75
.RE
.PP
\fBline_selection\fR
.RS 4
цвет, используемый для индикации выбранных строк
.sp
По умолчанию:
0\&.7 0\&.7 1
.RE
.PP
\fBmap_background\fR
.RS 4
цвет фона для области отображения
.sp
По умолчанию:
0\&.6 0\&.6 0\&.6
.RE
.PP
\fBmargin\fR
.RS 4
цвет, используемый для индикации правого поля
.sp
По умолчанию:
0\&.8 0\&.8 0\&.8
.RE
.PP
\fBpreedit\fR
.RS 4
цвет предредактируемого текста
.sp
По умолчанию:
0 0 0
.RE
.PP
\fBtext\fR
.RS 4
цвет обычного текста
.sp
По умолчанию:
0 0 0
.RE
.PP
\fBtext_background\fR
.RS 4
цвет фона для текстовой области
.sp
По умолчанию:
1 1 1
.RE
.RE
.SS "Значения с Плавающей Точкой"
.PP
\fBfloat \fR\fB\fIname\fR\fR\fB \fR\fB\fIvalue\fR\fR
.RS 4
Объявить ресурс с плавающей точкой, называемый
\fIname\fR
со значением
\fIvalue\fR\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBИспользуемые Ресурсы с Плавающей Точкой\fR
.RS 4
.PP
Следующие ресурсы с плавающей точкой используются программой
Diffuse:
.PP
\fBalignment_opacity\fR
.RS 4
непрозрачность, используемая при составлении цвета ручного выравнивания
.sp
По умолчаниям:
1
.RE
.PP
\fBcharacter_difference_opacity\fR
.RS 4
непрозрачность, используемая при составлении цветов различия символов
.sp
По умолчаниям:
0\&.4
.RE
.PP
\fBcharacter_selection_opacity\fR
.RS 4
непрозрачность, используемая при составлении цвета выбора символа
.sp
По умолчаниям:
0\&.4
.RE
.PP
\fBedited_opacity\fR
.RS 4
непрозрачность, используемая при составлении цвета отредактированной строки
.sp
По умолчаниям:
0\&.4
.RE
.PP
\fBline_difference_opacity\fR
.RS 4
непрозрачность, используемое при составлении цветов различия строк
.sp
По умолчаниям:
0\&.3
.RE
.PP
\fBline_selection_opacity\fR
.RS 4
непрозрачность, используемая при составлении цвета выбора строки
.sp
По умолчаниям:
0\&.4
.RE
.RE
.SS "Подсветка Синтаксиса"
.PP
\fBsyntax \fR\fB\fIname\fR\fR\fB \fR\fB[\fIinitial_state\fR \fIdefault_tag\fR]\fR
.RS 4
Объявить новый стиль синтаксиса, именуемый
\fIname\fR\&. Подсветка синтаксиса использует простой автомат с конечным числом состояний, который переходит из одного состояния в другое, когда определенные образчики являются сочетающимися\&. Начальное состояние для конечного автомата будет
\fIinitial_state\fR\&. Все символы, не соответствующие образчику, будут помечены как
\fIdefault_tag\fR
для подсветки\&. Стиль синтаксиса, называемый
\fIname\fR, может быть удален опусканием
\fIinitial_state\fR
и
\fIdefault_tag\fR\&.
.RE
.PP
\fBsyntax_files \fR\fB\fIname\fR\fR\fB \fR\fB[\fIpattern\fR]\fR
.RS 4
Определяет, что файлы с соответствием имени
\fIpattern\fR
должны быть подсвечены с использованием стиля синтаксиса, называемого
\fIname\fR\&. Образчики, чтобы сопоставить файлы для использования со стилем синтаксиса, называемым
\fIname\fR, могут быть удалены опусканием
\fIpattern\fR\&.
.RE
.PP
\fBsyntax_magic \fR\fB\fIname\fR\fR\fB \fR\fB[\fIpattern\fR [ignorecase]]\fR
.RS 4
Определяет, что файлы с первой строкой, соответствующей
\fIpattern\fR, должны быть подсвечены с использованием стиля синтаксиса, называемым
\fIname\fR\&. Образчики, чтобы сопоставить файлы для использования со стилем синтаксиса, называемым
\fIname\fR, могут быть удалены опусканием
\fIpattern\fR\&.
.RE
.PP
\fBsyntax_pattern \fR\fB\fIname\fR\fR\fB \fR\fB\fIinitial_state\fR\fR\fB \fR\fB\fIfinal_state\fR\fR\fB \fR\fB\fItag\fR\fR\fB \fR\fB\fIpattern\fR\fR\fB \fR\fB[ignorecase]\fR
.RS 4
Добавляет образчик к ранее объявленному стилю синтаксиса\&. Образчики пробуются по одному в порядке, в которым они были объявлены, пока первое соответствиене будет найдено\&. Образчик будет использоваться только для сопоставления символов, если конечный автомат будет в состоянии
\fIinitial_state\fR\&. Конечный автомат перейдет в состояние
\fIfinal_state\fR, если определяемый
\fIpattern\fR
образчик будет соответствующим\&. Будет использоваться нечувствительное к регистру сопоставление с образчиком, если определено
\fBignorecase\fR\&. Все символы, соответствующие образчику, будут помечены как тег для подсветки\&.
.RE
.SH "ФАЙЛЫ"
.PP
Следующие файлы используются программой
Diffuse:
.PP
/etc/diffuserc
.RS 4
общесистемные инициализации (%INSTALL_DIR%\ediffuserc
на Microsoft Windows)
.RE
.PP
/usr/share/diffuse/syntax/*\&.syntax
.RS 4
файлы синтаксиса для различных языков программирования (%INSTALL_DIR%\esyntax\e*\&.syntax
на Microsoft Windows)
.RE
.PP
~/\&.config/diffuse/diffuserc
.RS 4
ваши инициализации (%HOME%\e\&.config\ediffuse\ediffuserc
на Microsoft Windows)
.RE
.PP
~/\&.config/diffuse/prefs
.RS 4
ваши сохраненные предпочтения (%HOME%\e\&.config\ediffuse\eprefs
на Microsoft Windows)
.RE
.PP
~/\&.local/share/diffuse/state
.RS 4
данные, не изменяемые на сеансах (%HOME%\e\&.local\eshare\ediffuse\estate
на Microsoft Windows)
.RE
.SH "АВТОРЫ"
.PP
Программа
Diffuse
написана Derrick Moser
<derrick_moser@yahoo\&.com>\&.
.PP
\(co 2006\-2014 Derrick Moser\&. Все Права Защищены\&.
.PP
Русификация (diffuse\&.mo; ru\&.po): О\&.Ю\&.Пахтусов
<oupakhtusov@gmail\&.com>
.SH "КОПИРОВАНИЕ"
.PP
Diffuse
является бесплатным Программным Обеспечением (ПО); можно распространять программу и/или изменять ее в соответствии с
GNU General Public License, как опубликовано Free Software Foundation; либо версия 2 лицензии, либо (по вашему выбору) любая более поздняя версия\&.
