name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get -y install libgirepository1.0-dev
        pip install -r requirements.dev.txt
        pip list

    - name: Flake8
      run: |
        flake8 --version
        flake8 src/ po/

    - name: MyPy
      run: |
        mypy --version
        mypy src/ po/

  meson-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.8'
    - run: sudo apt-get -y install meson appstream desktop-file-utils gettext
    - run: pip install meson ninja
    - run: meson setup build
    - run: meson compile -C build
    - run: meson test --print-errorlogs -C build

  flatpak-build-test:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.8'
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: "diffuse.flatpak"
        manifest-path: "io.github.mightycreak.Diffuse.yml"
        cache-key: flatpak-builder-${{ github.sha }}
        run-tests: "true"
