name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        sudo apt-get -y install libgirepository1.0-dev appstream appstream-util desktop-file-utils gettext
        pip install -r requirements.txt

    - name: Meson build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        setup-options: --prefix=/tmp/diffuse

    - name: Meson test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test

    - name: Meson install
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: install

    - name: Flake8
      run: |
        flake8 /tmp/diffuse/
        flake8 po/

    - name: MyPy
      run: |
        mypy /tmp/diffuse/
        mypy po/

  flatpak-build-test:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Flatpak builder
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: "diffuse.flatpak"
        manifest-path: "io.github.mightycreak.Diffuse.yml"
        cache-key: flatpak-builder-${{ github.sha }}
        run-tests: "true"
